runtime: python39  # or python38 for Python 3.8
env: standard
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2
automatic_scaling:
  max_instances: 5

env_variables:
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres:aliza@/final_project?host=127.0.0.1:5433"
  SECRET_KEY: "alizameller"
